#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : perl-MooseX-Types-LoadableClass
Version  : 0.016
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Types-LoadableClass-0.016.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Types-LoadableClass-0.016.tar.gz
Summary  : 'ClassName type constraint with coercion to load the class.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-MooseX-Types-LoadableClass-license = %{version}-%{release}
Requires: perl-MooseX-Types-LoadableClass-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(ExtUtils::Config)
BuildRequires : perl(ExtUtils::Helpers)
BuildRequires : perl(ExtUtils::InstallPaths)
BuildRequires : perl(Module::Build::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution MooseX-Types-LoadableClass,
version 0.016:

%package dev
Summary: dev components for the perl-MooseX-Types-LoadableClass package.
Group: Development
Provides: perl-MooseX-Types-LoadableClass-devel = %{version}-%{release}
Requires: perl-MooseX-Types-LoadableClass = %{version}-%{release}

%description dev
dev components for the perl-MooseX-Types-LoadableClass package.


%package license
Summary: license components for the perl-MooseX-Types-LoadableClass package.
Group: Default

%description license
license components for the perl-MooseX-Types-LoadableClass package.


%package perl
Summary: perl components for the perl-MooseX-Types-LoadableClass package.
Group: Default
Requires: perl-MooseX-Types-LoadableClass = %{version}-%{release}

%description perl
perl components for the perl-MooseX-Types-LoadableClass package.


%prep
%setup -q -n MooseX-Types-LoadableClass-0.016
cd %{_builddir}/MooseX-Types-LoadableClass-0.016

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-MooseX-Types-LoadableClass
cp %{_builddir}/MooseX-Types-LoadableClass-%{version}/LICENCE %{buildroot}/usr/share/package-licenses/perl-MooseX-Types-LoadableClass/92fce6be76aebcf68c70654f0fe28fa8548e574c || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/MooseX::Types::LoadableClass.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-MooseX-Types-LoadableClass/92fce6be76aebcf68c70654f0fe28fa8548e574c

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
